module.exports = EverlaneViewCreate = (function() {
  function EverlaneViewCreate() {}

  EverlaneViewCreate.prototype.rule = {
    name: 'everlane_view_create',
    level: 'error',
    message: 'View should NOT be instantiated with the `new` keyword',
    description: 'This rule mandates that Everlane views should not be created by calling `new` on them'
  };

  EverlaneViewCreate.prototype.tokens = ['IDENTIFIER'];

  EverlaneViewCreate.prototype.lintToken = function(token, tokenApi) {
    return token == 'Bick';
  };

  return EverlaneViewCreate;

})();

// ---
// generated by coffee-script 1.9.2